name: Docker
on:
  push:
    tags:
      - "*.*.*"
    branches:
      - "main"
jobs:
  docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Generate Alpine Docker tag
        id: docker_alpine_tag
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/lobsters-base
          DOCKER_VERSION=dev
          TAGS="${DOCKER_IMAGE}:${DOCKER_VERSION}"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            DOCKER_VERSION=${GITHUB_REF#refs/tags/}
            TAGS="${DOCKER_IMAGE}:${DOCKER_VERSION},${DOCKER_IMAGE}:latest"
          fi
          echo "TAGS=${TAGS}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Alpine images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker_alpine_tag.outputs.TAGS }}
